---
extends: airbnb
plugins:
  - react
  - react-native
parser: babel-eslint
env:
  jest: true
rules:
  react/jsx-filename-extension:
    - 2
    - extensions:
        - .js
        - .jsx
  react/prefer-stateless-function:
    - 0
  react/jsx-one-expression-per-line:
    - 0
